#!/bin/sh

. $(dirname $0)/adc.common-functions

[ -z "$1" ] && die "A repository path must be supplied."

remove=$1

get_rights_and_owner $remove
[ "$perm_remove" = "yes" ] || die "$remove is not yours to remove!"

cd $GL_REPO_BASE_ABS
rm -rf $remove.git
