#!/bin/sh

. $(dirname $0)/adc.common-functions

[ -z "$1" ] && die "A repository path must be supplied."

delete=$1

get_rights_and_owner $delete
[ "$perm_create" = "yes" ] || die "$delete is not yours to delete!"

cd $GL_REPO_BASE_ABS
rm -rf $delete.git
